"""Markdown rendering.

The layout puts guidance first because that is the thing you cannot get from a
screener, and keeps exact figures visually separate from model-written prose so
it is always obvious which is which.
"""

from __future__ import annotations

from earnings_agent.edgar import Filing
from earnings_agent.llm import Brief
from earnings_agent.xbrl import INCOME_CONCEPTS, Fact, Financials

STATUS_LABEL = {
    "written_guidance_found": "written guidance found",
    "no_written_guidance": "no written guidance in this release",
    "issuer_does_not_guide": "issuer does not provide guidance",
    "unclear": "unclear",
}


def _pct(v: float | None) -> str:
    return f"{v:+.1f}%" if v is not None else "n/a"


UNIT = {
    "revenue_yoy_pct": "% YoY", "gross_margin_pct": "%", "operating_margin_pct": "%",
    "net_margin_pct": "%", "price_return_pct": "%", "revenue_usd": " USD",
    "eps_diluted_usd": " USD", "qualitative": "",
}
MARK = {"hit": "correct", "miss": "wrong", "pending": "pending", "unresolvable": "manual"}


def render_thesis(ticker: str, thesis, peers_used: list[str],
                  model: str | None, claims: list | None = None) -> str:
    """Render a thesis. Kept visually distinct from a brief - this is argument,
    not extraction, and the reader should never be in doubt which they hold."""
    out: list[str] = []
    out.append(f"# {ticker} — thesis  *(speculative)*")
    out.append("")
    out.append(
        "> Unlike a brief, nothing here is quote-backed or checkable against a filing. "
        "It is an argument from the filings, and it may be wrong. The claims below exist "
        "so it can be scored later."
    )
    out.append("")
    out.append(f"**{thesis.direction.upper()}** · confidence **{thesis.confidence}**")
    out.append("")
    out.append(thesis.summary)
    out.append("")
    out.append("## Reasoning")
    out.append(thesis.reasoning)
    out.append("")

    if thesis.rests_on:
        out.append("### Rests on")
        for r in thesis.rests_on:
            out.append(f"- {r}")
        out.append("")

    if thesis.peer_signals:
        out.append(f"### Peer evidence ({', '.join(peers_used) or 'none'})")
        for p in thesis.peer_signals:
            out.append(f"- **{p.ticker}** — {p.signal}")
            out.append(f"  - > {p.quote}")
        out.append("")
    elif not peers_used:
        out.append("### Peer evidence")
        out.append("_None — this thesis saw one company in isolation._")
        out.append("")

    out.append("## Falsifiable claims")
    out.append("")
    out.append("| Claim | Check | Settles | Status |")
    out.append("|---|---|---|---|")
    settled = claims or []
    for i, c in enumerate(thesis.claims):
        unit = UNIT.get(c.check, "")
        chk = ("—" if c.check == "qualitative"
               else f"{c.check} {c.comparator} {c.threshold:g}{unit}")
        horizon = f"+{c.horizon_quarters}Q"
        status = "pending"
        if i < len(settled):
            row = settled[i]
            status = MARK.get(row["status"], row["status"])
            if row["actual"] is not None:
                status += f" ({row['actual']:,.1f})"
        out.append(f"| {c.statement} | `{chk}` | {horizon} | {status} |")
    out.append("")

    for c in thesis.claims:
        out.append(f"- **Disconfirms** ({c.statement[:60]}…): {c.disconfirms}")
    out.append("")

    out.append("## Key uncertainty")
    out.append(thesis.key_uncertainty)
    out.append("")
    out.append("## What this cannot see")
    out.append(thesis.what_we_cannot_see)
    out.append("")
    out.append("---")
    out.append(f"Generated by {model or 'unknown'} from filings only. "
               f"Peers supplied: {', '.join(peers_used) or 'none'}.")
    return "\n".join(out)


def render(
    filing: Filing,
    fin: Financials,
    press_release_url: str | None,
    brief: Brief | None,
    model: str | None,
    transcript_state: str = "pending",
) -> str:
    out: list[str] = []
    period = fin.period_end("quarter")

    out.append(f"# {filing.ticker} — earnings brief")
    accepted = filing.acceptance_dt or filing.filing_date
    src = f"[press release]({press_release_url})" if press_release_url else "no EX-99 exhibit"
    out.append(
        f"`{filing.form}` Item {filing.items} · accepted {accepted} · "
        f"period ending {period} · {src}"
    )
    out.append("")

    # -- guidance --------------------------------------------------------
    out.append("## Forward guidance")
    if brief is None:
        out.append("_Narrative extraction unavailable — no LLM key configured, "
                   "or extraction failed. Figures below are unaffected._")
    else:
        label = STATUS_LABEL.get(brief.guidance_status, brief.guidance_status)
        out.append(f"**{label}** — {brief.guidance_status_note}")
        out.append("")
        if brief.guidance:
            for g in brief.guidance:
                out.append(f"- **{g.metric}** ({g.period}): {g.value}")
                out.append(f"  - vs prior: {g.change_vs_prior}")
                out.append(f"  - > {g.quote}")
        else:
            out.append(
                "_No forward guidance in the written release. If this issuer guides "
                "verbally, the figure will only appear once the call transcript lands._"
            )
    out.append("")

    # -- exact numbers ---------------------------------------------------
    out.append("## Reported figures")
    out.append("")
    out.append("_Exact values from SEC XBRL. Not model-generated._")
    out.append("")

    rows, missing = fin.income_statement("quarter")
    growth = {c: (p, l, pct) for c, p, l, pct in fin.growth_table("quarter")}
    if rows:
        out.append("| Line | Quarter | YoY |")
        out.append("|---|---:|---:|")
        for f in rows:
            g = growth.get(f.concept)
            out.append(f"| {f.concept} | {f.format()} | {_pct(g[2]) if g else '—'} |")
        out.append("")

    ytd = [f for f in fin.ytd() if f.concept in ("Operating cash flow", "Capex")]
    if ytd:
        out.append("Cash flow is reported year-to-date, not quarterly:")
        out.append("")
        out.append("| Line | Year to date |")
        out.append("|---|---:|")
        for f in ytd:
            out.append(f"| {f.concept} | {f.format()} |")
        out.append("")

    still_missing = [c for c in missing if c not in {f.concept for f in ytd}]
    if still_missing:
        out.append(f"_Not reported for this period: {', '.join(still_missing)}._")
        out.append("")

    bs = fin.balance_sheet()
    if bs:
        out.append(f"### Balance sheet — as of {bs[0].end}")
        out.append("")
        out.append("| Line | Value |")
        out.append("|---|---:|")
        for f in bs:
            out.append(f"| {f.concept} | {f.format()} |")
        out.append("")

    # -- narrative -------------------------------------------------------
    if brief is not None:
        if brief.key_points:
            out.append("## Key points")
            for k in brief.key_points:
                out.append(f"- {k.point}")
                out.append(f"  - > {k.quote}")
            out.append("")
        if brief.watch_items:
            out.append("## Watch items")
            for w in brief.watch_items:
                out.append(f"- {w}")
            out.append("")
        if brief.tone_shift and brief.tone_shift.lower() != "nothing notable":
            out.append("## Tone")
            out.append(brief.tone_shift)
            out.append("")

    # -- provenance ------------------------------------------------------
    out.append("---")
    accns = sorted({f.accession for f in rows + bs})
    out.append(f"Figures: SEC XBRL companyfacts, filings {', '.join(accns) or 'n/a'}.")
    out.append(f"Narrative: {model or 'none'}, from the EX-99.1 press release only.")
    out.append(f"Call transcript: **{transcript_state}** — this brief did not wait for it.")
    return "\n".join(out)
